language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master

deploy:
  provider: heroku
  app: angular-project-marushevska
  api_key:
    secure: '912acbc0-7963-44c1-b43d-1db308ec202a'